### ISSUE TITLE
README.md link

### ISSUE THREAD

**Issue by nelsonspbr** [openshift/cluster-api-provider-libvirt#224] opened 2021-07-20 22:21 UTC
In `README.md`:

> Before running the installer make sure you set libvirt to use the host private ip uri above: https://github.com/openshift/installer/blob/master/examples/tectonic.libvirt.yaml#L14

Link is broken. Project `openshift/installer` does not have an `examples` directory anymore from what I can tell. Are these instructions documented anywhere else? Or maybe not needed anymore...

**Comment by cfergeau** [comment] 2021-07-28 16:14
This is a duplicate of https://github.com/openshift/cluster-api-provider-libvirt/issues/106.
I just created https://github.com/openshift/cluster-api-provider-libvirt/pull/225 for this. Had this on my disk for a while, but never created a PR :(

**Closed** 2021-12-25 22:21 UTC
Labels: lifecycle/rotten
